import { COLORS, FONT } from "./theme";

export const drawFooter = (doc) => {

  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;

  // ===============================
  // Divider Line
  // ===============================

  doc.setDrawColor(...COLORS.gray300);

  doc.line(
    20,
    pageHeight - 20,
    pageWidth - 20,
    pageHeight - 20
  );

  // ===============================
  // Footer Text
  // ===============================

  doc.setFontSize(FONT.small);
  doc.setTextColor(...COLORS.gray500);

  doc.text(
    "Generated by SkillMatch AI",
    20,
    pageHeight - 10
  );

  // ===============================
  // Generated Date
  // ===============================

  doc.text(
    new Date().toLocaleDateString(),
    pageWidth - 40,
    pageHeight - 10
  );

  // Reset Text Color
  doc.setTextColor(0);

};